// Usually, we define action types in this file.
const types = {
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_ERROR: "FETCH_PRODUCT_ERROR",
    FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",

    FETCH_PRODUCT_DETAIL_SUCCESS: "FETCH_PRODUCT_DETAIL_SUCCESS",
    FETCH_PRODUCT_DETAIL_ERROR: "FETCH_PRODUCT_DETAIL_ERROR",
    FETCH_PRODUCT_DETAIL_REQUEST: "FETCH_PRODUCT_DETAIL_REQUEST",

};

export default types;
