// Usually, we define action types in this file.
const types = {
    // Product
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_ERROR: "FETCH_PRODUCT_ERROR",
    FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",

    FETCH_PRODUCT_DETAIL_SUCCESS: "FETCH_PRODUCT_DETAIL_SUCCESS",
    FETCH_PRODUCT_DETAIL_ERROR: "FETCH_PRODUCT_DETAIL_ERROR",
    FETCH_PRODUCT_DETAIL_REQUEST: "FETCH_PRODUCT_DETAIL_REQUEST",

    // Category
    FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_ERROR: "FETCH_CATEGORY_ERROR",
    FETCH_CATEGORY_REQUEST: "FETCH_CATEGORY_REQUEST",

    // Login
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT: "LOGOUT",



};

export default types;
